name: Manual Sequence Workflow

on: 
  push:
    branches:
      - master

jobs:
  dev_build:
    name: Build Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Build Dev
      run: echo "Dev Built"

  dev_deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: dev_build
    steps:
    - name: Dev Deploy
      run: echo "Dev Deployed"

  stage_build:
    name: Build Staging
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
    - name: Build Staging
      run: echo "Staging Built"

  stage_deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: stage_build
    steps:
    - name: Staging Deploy
      run: echo "Staging Deployed"
